// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © sean80111108

//@version=4
strategy("Sean DMI v2 alt", overlay=true, default_qty_type = strategy.percent_of_equity, default_qty_value = 100, initial_capital = 1000, commission_type = strategy.commission.percent, commission_value = 0)
back_y = input(title="year",type=input.integer,defval = 2021)
back_m = input(title="month",type=input.integer,defval = 1)
back_d = input(title="day",type=input.integer,defval = 1)
back_start = timestamp(back_y,back_m,back_d,0,0,0)
len = input(title="length",type=input.integer,defval = 15)
adx_value = input(title="adx",type=input.integer,defval = 8)
[diplus,diminus,adx] = dmi(len,adx_value)

buy_signal = crossover(diplus, diminus)
sell_signal = crossunder(diplus, diminus)
buy_signal2 = diplus > diminus and adx > 15 and adx > adx[1]
sell_signal2 = diplus < diminus
b = abs(diplus - abs(diminus)) > 8

//Engulfing Candle
//Original Engulfing Candle
//bull close >= open[1] and close[1] < open[1]
//bear opposite
buy = close > open[1] and close > open[1] and close > open[2]
sell =  close < open[1] and close[1] > open[1] and close < open[2]  and close < open[3]

if time >= back_start
    if  buy
        strategy.entry("dmi 進場", long = true)
    if  buy_signal or buy_signal2
        strategy.entry("dmi 進場", long = true)
    if  sell 
        strategy.close("dmi 進場")
    if  sell_signal2
        strategy.close("dmi 進場")

   
