// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © sean80111108

//@version=4
strategy(title="MACD", shorttitle="MACD", initial_capital=2500 ,default_qty_type = strategy.percent_of_equity, default_qty_value = 60,overlay=true)

back_y = input(title="year",type=input.integer,defval = 2020)
back_m = input(title="month",type=input.integer,defval = 1)
back_d = input(title="day",type=input.integer,defval = 1)

back_start = timestamp(back_y,back_m,back_d,0,0,0)

//macd
dif = ema(close,12)-ema(close,36)
macd = ema(dif,9)
macd_buy = crossover(dif,macd)
macd_sell = crossunder(dif,macd)
if time >= back_start
    strategy.entry("進場", true,when=macd_buy, comment = "macd 進場")
    strategy.close("進場", when = macd_sell,comment="macd 出場")
